import { internal } from './_generated/api'
import { internalMutation } from './_generated/server'

const CATEGORIES = [
  // ─── Universal categories (from reference app) ─────────────────────
  {
    name: 'Styles',
    scope: 'universal' as const,
    sortOrder: 1,
    options: [
      '3D Render',
      'Abstract',
      'Anime',
      'Art Deco',
      'Art Nouveau',
      'Baroque',
      'Brutalist',
      'Cartoon',
      'Charcoal',
      'Cinematic',
      'Clay',
      'Collage',
      'Comic Book',
      'Concept Art',
      'Cubism',
      'Cyberpunk',
      'Digital Art',
      'Fantasy',
      'Flat Design',
      'Futuristic',
      'Glitch Art',
      'Gothic',
      'Graffiti',
      'Hyperrealistic',
      'Illustration',
      'Impressionist',
      'Isometric',
      'Low Poly',
      'Minimalist',
      'Neon',
      'Oil Painting',
      'Paper Cut',
      'Pencil Sketch',
      'Photorealistic',
      'Pixel Art',
      'Pop Art',
      'Steampunk',
      'Surrealism',
      'Watercolor',
    ],
  },
  {
    name: 'Genres',
    scope: 'universal' as const,
    sortOrder: 2,
    options: [
      'Action',
      'Adventure',
      'Biography',
      'Comedy',
      'Crime',
      'Documentary',
      'Drama',
      'Experimental',
      'Family',
      'Fantasy',
      'Film Noir',
      'Historical',
      'Horror',
      'Independent',
      'Musical',
      'Mystery',
      'Noir',
      'Period Piece',
      'Political',
      'Romance',
      'Satire',
      'Sci-Fi',
      'Short Film',
      'Silent Film',
      'Slapstick',
      'Sports',
      'Superhero',
      'Thriller',
      'War',
      'Western',
      'Workplace Comedy',
      'Zombie',
    ],
  },
  {
    name: 'Places',
    scope: 'universal' as const,
    sortOrder: 3,
    options: [
      'Beach',
      'Car Interior',
      'Castle',
      'City Skyline',
      'Countryside',
      'Desert',
      'Forest',
      'Garden',
      'Home Interior',
      'Hospital',
      'Laboratory',
      'Library',
      'Mars',
      'Mountain',
      'Office',
      'Park',
      'Space Station',
      'Street',
      'Subway',
      'Underwater',
      'Workplace',
    ],
  },
  {
    name: 'Camera Settings',
    scope: 'universal' as const,
    sortOrder: 4,
    options: [
      'Aerial Shot',
      'Bird Eye View',
      'Bokeh',
      'Close-Up',
      'Dutch Angle',
      'Extreme Close-Up',
      'Fast Shutter Speed',
      'Fish Eye',
      'Long Exposure',
      'Macro',
      'Motion Blur',
      'Over the Shoulder',
      'Panoramic',
      'Sigma 85mm f/1.4',
      'Tilt-Shift',
      'Tilted Frame',
      'Wide Angle',
      '300mm Lens',
    ],
  },
  {
    name: 'Artists',
    scope: 'universal' as const,
    sortOrder: 5,
    options: [
      'Andy Warhol',
      'Boris Vallejo',
      'Da Vinci',
      'Edward Hopper',
      'Frida Kahlo',
      'Greg Rutkowski',
      'HR Giger',
      'Leonid Afremov',
      'Michelangelo',
      'Monet',
      'Picasso',
      'Raphael',
      'Rembrandt',
      'Roy Lichtenstein',
      'Salvador Dali',
      'Van Gogh',
      'Yayoi Kusama',
    ],
  },
  {
    name: 'Era',
    scope: 'universal' as const,
    sortOrder: 6,
    options: [
      '1920s',
      '1950s',
      '1970s',
      '1980s',
      '2000s',
      'Ancient',
      'Future',
      'Medieval',
      'Victorian',
    ],
  },

  // ─── RISE-specific categories ──────────────────────────────────────
  {
    name: 'Product',
    scope: 'rise' as const,
    sortOrder: 7,
    options: [
      'PUSH Adjustable Bed',
      'RISE Branding / Logo',
      'PUSH Characters',
      'RISE Office Interior',
      'PUSH Product Packaging',
    ],
  },
  {
    name: 'Shot Type',
    scope: 'rise' as const,
    sortOrder: 8,
    options: [
      'Close-Up',
      'Wide',
      'Medium',
      'Over the Shoulder',
      'POV',
      'Establishing',
      'Insert',
      'Two-Shot',
    ],
  },
  {
    name: 'Mood / Lighting',
    scope: 'rise' as const,
    sortOrder: 9,
    options: [
      'Warm',
      'Cool',
      'Dramatic',
      'Soft',
      'Neon',
      'Morning',
      'Night',
      'Golden Hour',
      'Overcast',
      'Candlelight',
      'Studio Lighting',
    ],
  },
]

export const seedPromptCategories = internalMutation({
  args: {},
  handler: async (ctx) => {
    for (const category of CATEGORIES) {
      await ctx.runMutation(internal.promptCategories.upsertCategory, category)
    }
  },
})

export const seedTheRemoteProject = internalMutation({
  args: {},
  handler: async (ctx) => {
    // Check if "PUSH" project already exists
    const existing = await ctx.db.query('projects').take(100)

    const match = existing.find((p) => p.name === 'PUSH')
    if (match) return match._id

    return await ctx.db.insert('projects', {
      name: 'PUSH',
      description:
        '54-shot AI comedy short about a man and his smart adjustable bed',
      type: 'film',
      createdBy: 'system',
    })
  },
})
