import Link from 'next/link'

export default function RootNotFound() {
  return (
    <main
      style={{
        background: '#000',
        minHeight: '100vh',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '40px 24px',
        fontFamily:
          "var(--font-dm-sans), -apple-system, BlinkMacSystemFont, 'DM Sans', sans-serif",
        position: 'relative',
        overflow: 'hidden',
      }}
    >
      {/* Grain */}
      <div
        style={{
          position: 'fixed',
          inset: 0,
          opacity: 0.02,
          pointerEvents: 'none',
          zIndex: 0,
          backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)'/%3E%3C/svg%3E")`,
          backgroundSize: '128px 128px',
        }}
      />

      <style>{`
        @keyframes bedReturn {
          0%   { width: 0; opacity: 0; }
          15%  { opacity: 1; }
          100% { width: 120px; opacity: 0; }
        }
      `}</style>

      <div
        style={{
          position: 'relative',
          zIndex: 1,
          textAlign: 'center',
          maxWidth: '480px',
        }}
      >
        {/* Giant faded 404 */}
        <div
          style={{
            fontSize: 'clamp(6rem, 20vw, 12rem)',
            fontWeight: 600,
            letterSpacing: '-0.04em',
            lineHeight: 1,
            color: 'rgba(255,255,255,0.03)',
            userSelect: 'none',
            marginBottom: '-20px',
          }}
        >
          404
        </div>

        <p
          style={{
            fontSize: '13px',
            color: 'rgba(255,255,255,0.5)',
            lineHeight: 1.7,
            marginBottom: '24px',
          }}
        >
          The page you&rsquo;re looking for is not at this address.
        </p>

        <div
          style={{
            fontSize: '10px',
            color: 'rgba(255,255,255,0.2)',
            lineHeight: 1.8,
            marginBottom: '32px',
          }}
        >
          <p>Push Mode navigated here on your behalf.</p>
          <p>The page was not present.</p>
          <p style={{ marginTop: '8px' }}>The bed is returning.</p>
        </div>

        {/* Animated blue line — the bed returning */}
        <div
          style={{
            display: 'flex',
            justifyContent: 'center',
            marginBottom: '40px',
            height: '1px',
          }}
        >
          <div
            style={{
              height: '1px',
              background: 'rgba(42,92,219,0.5)',
              animation: 'bedReturn 3s ease-in-out infinite',
            }}
          />
        </div>

        <Link
          href="/"
          style={{
            display: 'inline-block',
            fontSize: '10px',
            letterSpacing: '0.14em',
            textTransform: 'uppercase',
            color: 'rgba(255,255,255,0.2)',
            textDecoration: 'none',
            padding: '10px 24px',
            border: '1px solid rgba(255,255,255,0.08)',
            borderRadius: '980px',
            transition: 'color 0.2s ease',
          }}
        >
          Return Home
        </Link>

        <p
          style={{
            fontSize: '8px',
            color: 'rgba(255,255,255,0.08)',
            marginTop: '60px',
            lineHeight: 1.8,
            maxWidth: '280px',
            marginLeft: 'auto',
            marginRight: 'auto',
          }}
        >
          This message was generated by Push Mode on behalf of RISE. Push Mode
          determines the most productive next step. In this case, the step was
          not found. Push Mode has noted this outcome and will adjust future
          routing accordingly. This is a feature, not a limitation.
        </p>
      </div>
    </main>
  )
}
