import { LABELS, MUTUAL_EXCLUSIONS } from "./pipeline-states.js";

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", "'\"'\"'")}'`;
}

export function renderPipelineLabelShell(): string {
  const lines = [
    "#!/usr/bin/env bash",
    "# Generated by shft/engine/lib/render-pipeline-artifacts.ts from pipeline-states.ts.",
    "# Do not edit by hand; update pipeline-states.ts and regenerate.",
    "",
    "declare -A LABEL_APPLIES_TO=(",
    ...Object.entries(LABELS).map(
      ([label, def]) => `  [${shellQuote(label)}]=${shellQuote(def.appliesTo.join(","))}`,
    ),
    ")",
    "",
    "MUTUAL_EXCLUSIONS=(",
    ...MUTUAL_EXCLUSIONS.map(([left, right]) => `  ${shellQuote(`${left}|${right}`)}`),
    ")",
    "",
  ];

  return lines.join("\n");
}

export function renderLabelCatalogJson(): string {
  const labels = Object.entries(LABELS).map(([name, def]) => ({
    name,
    color: def.color,
    description: def.description,
  }));

  return `${JSON.stringify(labels, null, 2)}\n`;
}
